baseURL = 'https://sp4sci.github.io/'
languageCode = 'en-us'
title = "SP4Sci '26"
theme = 'beautifulhugo'

[params]
    subtitle = "The first workshop on Scalable Performance, Portability, and Productivity for Scientific Computing co-located with Computing Frontiers '26"
    logo = "image/logo.png"
    [params.author]
        name = "Workshop Organizers"

[frontmatter]
    lastmod = [":git", ":fileModTime", ":default"]

[[menu.main]]
    name = "Author's guide"
    url = "author_guide"
    weight = 1

[[menu.main]]
    name = "Dates"
    url = "dates"
    weight = 1

[[menu.main]]
    name = "Contacts"
    url = "contacts"
    weight = 1

[[menu.main]]
    name = "Venue"
    url = "venue"
    weight = 1

[[menu.main]]
    name = "Submit"
    url = "submit"
    weight = 1
