languageCode = 'en-us'
title = "SP4Sci '26"
theme = 'beautifulhugo'
canonifyURLs = true
relativeURLs = false

[params]
    subtitle = "The first workshop on Scalable Performance, Portability, and Productivity for Scientific Computing co-located with Computing Frontiers '26"
    logo = "image/logo.png"
    [params.author]
        name = "Workshop Organizers"

[frontmatter]
    lastmod = [":git", ":fileModTime", ":default"]

[menu]
    [[menu.main]]
        name = "Author's guide"
        pageRef = "author_guide"
        weight = 1

    [[menu.main]]
        name = "Dates"
        pageRef = "dates"
        weight = 2

    [[menu.main]]
        name = "Contacts"
        pageRef = "contacts"
        weight = 3

    [[menu.main]]
        name = "Venue"
        pageRef = "venue"
        weight = 4

    [[menu.main]]
        name = "Submit"
        pageRef = "submit"
        weight = 5
